"""Report session management for JAVDB AutoSpider.

Handles ReportSessions, ReportMovies, and ReportTorrents tables in reports.db.

ReportSessions tracks each pipeline run with metadata (report type, date, URL,
status, run identity). Each session can be in one of these states:
- 'in_progress' — Session is active
- 'finalizing' — Pending writes are being committed
- 'committed' — Session completed successfully
- 'failed' — Session failed (marked before rollback)

ReportMovies and ReportTorrents store the snapshot of movies and torrents
discovered in each run (used for CSV report generation).
"""

import os
import time
from datetime import datetime
import sqlite3
from typing import Dict, List, Optional, Tuple

from packages.python.javdb_platform.config_helper import cfg
from packages.python.javdb_platform.logging_config import get_logger

logger = get_logger(__name__)

# Lazy imports to avoid circular dependencies
_get_db = None
_get_local_sqlite_db = None
_REPORTS_DB_PATH = None
_HISTORY_DB_PATH = None
_generate_session_id = None
_resolve_write_mode = None
_DB_OPERATIONAL_ERRORS = None


def _ensure_imports():
    """Lazy import to avoid circular dependency with db_connection and db_session."""
    global _get_db, _get_local_sqlite_db, _REPORTS_DB_PATH, _HISTORY_DB_PATH
    global _generate_session_id, _resolve_write_mode, _DB_OPERATIONAL_ERRORS
    if _get_db is None:
        from packages.python.javdb_platform.db_connection import (
            get_db,
            get_local_sqlite_db,
            REPORTS_DB_PATH,
            HISTORY_DB_PATH,
        )
        from packages.python.javdb_platform.db_session import (
            generate_session_id,
            _resolve_write_mode as resolve_wm,
        )
        _get_db = get_db
        _get_local_sqlite_db = get_local_sqlite_db
        _REPORTS_DB_PATH = REPORTS_DB_PATH
        _HISTORY_DB_PATH = HISTORY_DB_PATH
        _generate_session_id = generate_session_id
        _resolve_write_mode = resolve_wm

        try:
            from packages.python.javdb_platform.d1_client import D1PermanentError
            _DB_OPERATIONAL_ERRORS = (sqlite3.OperationalError, D1PermanentError)
        except ImportError:
            _DB_OPERATIONAL_ERRORS = (sqlite3.OperationalError,)


# ── Session creation ─────────────────────────────────────────────────────


def db_create_report_session(
    report_type: str,
    report_date: str,
    csv_filename: str,
    *,
    url_type: Optional[str] = None,
    display_name: Optional[str] = None,
    url: Optional[str] = None,
    start_page: Optional[int] = None,
    end_page: Optional[int] = None,
    created_at: Optional[str] = None,
    db_path: Optional[str] = None,
    run_id: Optional[str] = None,
    run_attempt: Optional[int] = None,
    session_id: Optional[str] = None,
    write_mode: Optional[str] = None,
) -> str:
    """Create a new report session and return its id.

    The Id is generated by the application (via generate_session_id()) and
    inserted explicitly, so SQLite and Cloudflare D1 see the same value.

    Args:
        report_type: Type of report ('daily', 'adhoc', etc.)
        report_date: Report date (YYYY-MM-DD)
        csv_filename: CSV filename for this session
        url_type: Optional URL type
        display_name: Optional display name
        url: Optional source URL
        start_page: Optional start page number
        end_page: Optional end page number
        created_at: Optional creation timestamp (defaults to now)
        db_path: Database path (defaults to REPORTS_DB_PATH)
        run_id: GitHub Actions run_id (optional)
        run_attempt: GitHub Actions run_attempt (optional)
        session_id: Optional explicit session ID (for migration tool)
        write_mode: 'audit' or 'pending' (defaults to env var or 'audit')

    Returns:
        Session ID (TEXT format)

    Raises:
        RuntimeError: If JAVDB_FORBID_DB_WRITES=1 is set
    """
    _ensure_imports()

    from packages.python.javdb_platform.config_helper import db_writes_forbidden
    if db_writes_forbidden():
        raise RuntimeError(
            "db_create_report_session refused: "
            "JAVDB_FORBID_DB_WRITES=1 is engaged. This kill switch is "
            "set by smoke-test workflows (TestIngestion) that must not "
            "pollute production D1 / SQLite. Unset it if you really "
            "need to write to a database."
        )

    if created_at is None:
        created_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    sid = session_id if session_id is not None else _generate_session_id()
    resolved_mode = _resolve_write_mode(write_mode)

    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        conn.execute(
            """INSERT INTO ReportSessions
               (Id, ReportType, ReportDate, UrlType, DisplayName,
                Url, StartPage, EndPage, CsvFilename, DateTimeCreated,
                Status, RunId, RunAttempt, WriteMode)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'in_progress', ?, ?, ?)""",
            (sid, report_type, report_date, url_type, display_name,
             url, start_page, end_page, csv_filename, created_at,
             run_id, run_attempt, resolved_mode),
        )
    return sid


# ── Session status updates ───────────────────────────────────────────────


def db_mark_session_committed(
    session_id: str,
    db_path: Optional[str] = None,
) -> int:
    """Mark a session as 'committed' so it survives any future cleanup.

    Once a session is committed, its audit rows in MovieHistoryAudit /
    TorrentHistoryAudit are pruned (the rollback CLI refuses committed
    sessions anyway, so the audit log is no longer needed).

    Args:
        session_id: Session identifier
        db_path: Database path (defaults to REPORTS_DB_PATH)

    Returns:
        Number of ReportSessions rows updated (0 if not found or already committed)
    """
    _ensure_imports()

    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        cur = conn.execute(
            "UPDATE ReportSessions SET Status='committed' WHERE Id=? "
            "AND Status IS NOT 'committed'",
            (session_id,),
        )
        marked = cur.rowcount or 0

    # Audit retention: prune audit rows for this session even when the
    # ReportSessions update was a no-op (Status was already 'committed' on
    # a previous call). Keeps the tables bounded if commit is retried.
    try:
        with _get_db(_HISTORY_DB_PATH) as conn:
            mh = conn.execute(
                "DELETE FROM MovieHistoryAudit WHERE SessionId=?",
                (session_id,),
            )
            th = conn.execute(
                "DELETE FROM TorrentHistoryAudit WHERE SessionId=?",
                (session_id,),
            )
        pruned = (mh.rowcount or 0) + (th.rowcount or 0)
        if pruned > 0:
            logger.info(
                "Pruned %d audit row(s) on commit of session %s",
                pruned, session_id,
            )
    except Exception as exc:  # noqa: BLE001 - best-effort retention
        logger.warning(
            "Could not prune audit rows for committed session %s: %s",
            session_id, exc,
        )

    return marked


def db_mark_session_failed(
    session_id: str,
    db_path: Optional[str] = None,
    *,
    reason: Optional[str] = None,
) -> int:
    """Mark a session as 'failed' (debug-only flag set right before delete).

    Args:
        session_id: Session identifier
        db_path: Database path (defaults to REPORTS_DB_PATH)
        reason: Optional failure reason (e.g., 'workflow_cancel', 'stale_timeout')

    Returns:
        Number of rows updated
    """
    _ensure_imports()

    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        cur = conn.execute(
            "UPDATE ReportSessions SET Status='failed', FailureReason=? "
            "WHERE Id=?",
            (reason, session_id),
        )
        return cur.rowcount or 0


# ── Session queries ──────────────────────────────────────────────────────


def db_get_session_status(
    session_id: str,
    *,
    db_path: Optional[str] = None,
) -> Optional[Tuple[str, str]]:
    """Return (WriteMode, Status) for session_id, or None if absent.

    Args:
        session_id: Session identifier
        db_path: Database path (defaults to REPORTS_DB_PATH)

    Returns:
        Tuple of (write_mode, status) or None if session not found
    """
    _ensure_imports()

    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        try:
            row = conn.execute(
                "SELECT COALESCE(WriteMode,'audit') AS WriteMode, Status "
                "FROM ReportSessions WHERE Id=?",
                (session_id,),
            ).fetchone()
        except _DB_OPERATIONAL_ERRORS:
            # Legacy schema without WriteMode column
            row = conn.execute(
                "SELECT Status FROM ReportSessions WHERE Id=?",
                (session_id,),
            ).fetchone()
            if row:
                return ("audit", row["Status"])
            return None
    if row:
        return (row["WriteMode"], row["Status"])
    return None


def db_find_in_progress_sessions(
    *,
    since: Optional[str] = None,
    db_path: Optional[str] = None,
    max_age_hours: Optional[float] = None,
    require_run_identity: bool = False,
) -> List[str]:
    """Return ReportSessions.Id rows still flagged 'in_progress'.

    Args:
        since: ISO timestamp to restrict search (sessions created >= since)
        db_path: Database path (defaults to REPORTS_DB_PATH)
        max_age_hours: Alternative window (sessions older than now - max_age_hours)
        require_run_identity: Only include sessions with non-empty RunId

    Returns:
        List of session IDs

    Raises:
        ValueError: If both since and max_age_hours are provided
    """
    _ensure_imports()

    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        if since and max_age_hours is not None:
            raise ValueError(
                "db_find_in_progress_sessions: pass either 'since' or "
                "'max_age_hours', not both"
            )
        run_identity_clause = (
            " AND RunId IS NOT NULL AND TRIM(RunId) != ''"
            if require_run_identity else ""
        )

        if max_age_hours is not None:
            cutoff_ts = time.time() - (max_age_hours * 3600)
            cutoff = datetime.utcfromtimestamp(cutoff_ts).strftime(
                "%Y-%m-%d %H:%M:%S"
            )
            rows = conn.execute(
                "SELECT Id FROM ReportSessions "
                "WHERE Status='in_progress' AND DateTimeCreated < ?"
                + run_identity_clause,
                (cutoff,),
            ).fetchall()
        elif since:
            rows = conn.execute(
                "SELECT Id FROM ReportSessions "
                "WHERE Status='in_progress' AND DateTimeCreated >= ?"
                + run_identity_clause,
                (since,),
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT Id FROM ReportSessions WHERE Status='in_progress'"
                + run_identity_clause,
            ).fetchall()
    return [r['Id'] for r in rows]


def db_find_stale_pending_sessions(
    *,
    db_path: Optional[str] = None,
    max_age_hours: float = 48.0,
    require_run_identity: bool = True,
) -> List[Tuple[str, str, str]]:
    """Return [(Id, Status, WriteMode), ...] for stale Phase 3 sessions.

    Used by cleanup_stale_in_progress to dispatch in_progress sessions to
    rollback and finalizing sessions to resume_commit.

    Args:
        db_path: Database path (defaults to REPORTS_DB_PATH)
        max_age_hours: Age threshold in hours (default 48)
        require_run_identity: Skip legacy rows with empty RunId

    Returns:
        List of (session_id, status, write_mode) tuples
    """
    _ensure_imports()

    cutoff_ts = time.time() - (max_age_hours * 3600)
    cutoff = datetime.utcfromtimestamp(cutoff_ts).strftime(
        "%Y-%m-%d %H:%M:%S",
    )
    run_identity_clause = (
        " AND RunId IS NOT NULL AND TRIM(RunId) != ''"
        if require_run_identity else ""
    )

    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        try:
            rows = conn.execute(
                "SELECT Id, Status, COALESCE(WriteMode,'audit') AS WriteMode "
                "FROM ReportSessions "
                "WHERE Status IN ('in_progress','finalizing') "
                "AND DateTimeCreated < ?" + run_identity_clause,
                (cutoff,),
            ).fetchall()
        except _DB_OPERATIONAL_ERRORS:
            # Legacy schema without WriteMode column
            rows = conn.execute(
                "SELECT Id, Status FROM ReportSessions "
                "WHERE Status IN ('in_progress','finalizing') "
                "AND DateTimeCreated < ?" + run_identity_clause,
                (cutoff,),
            ).fetchall()
            return [(r["Id"], r["Status"], "audit") for r in rows]
    return [
        (r["Id"], r["Status"], r["WriteMode"]) for r in rows
    ]


def db_count_in_progress_sessions_for_run(
    run_id: str,
    run_attempt: Optional[int] = None,
    *,
    db_path: Optional[str] = None,
) -> int:
    """Count 'in_progress' sessions belonging to a (RunId, RunAttempt) pair.

    Used by the spider self-check: a single workflow run must own at most
    one in-progress session at any given time.

    Args:
        run_id: GitHub Actions run_id
        run_attempt: GitHub Actions run_attempt (optional)
        db_path: Database path (defaults to REPORTS_DB_PATH)

    Returns:
        Count of in-progress sessions
    """
    _ensure_imports()

    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        if run_attempt is None:
            row = conn.execute(
                "SELECT COUNT(*) AS n FROM ReportSessions "
                "WHERE Status='in_progress' AND RunId=?",
                (run_id,),
            ).fetchone()
        else:
            row = conn.execute(
                "SELECT COUNT(*) AS n FROM ReportSessions "
                "WHERE Status='in_progress' AND RunId=? AND RunAttempt=?",
                (run_id, int(run_attempt)),
            ).fetchone()
    return int((row or {'n': 0})['n'] or 0)


# ── ReportMovies / ReportTorrents ────────────────────────────────────────


def db_insert_report_rows(
    session_id: str,
    rows: List[dict],
    db_path: Optional[str] = None,
) -> int:
    """Insert report rows into ReportMovies + ReportTorrents.

    Accepts rows in the legacy flat dict format with keys like
    hacked_subtitle, subtitle, etc. Each non-empty magnet
    becomes a separate ReportTorrents row.

    Args:
        session_id: Session identifier
        rows: List of movie dicts with torrent data
        db_path: Database path (defaults to REPORTS_DB_PATH)

    Returns:
        Number of movies inserted
    """
    _ensure_imports()

    from apps.api.parsers.common import javdb_absolute_url

    _CATS = [
        ('hacked_subtitle',    'size_hacked_subtitle',    'file_count_hacked_subtitle',    'resolution_hacked_subtitle',    1, 0),
        ('hacked_no_subtitle', 'size_hacked_no_subtitle', 'file_count_hacked_no_subtitle', 'resolution_hacked_no_subtitle', 0, 0),
        ('subtitle',           'size_subtitle',           'file_count_subtitle',           'resolution_subtitle',           1, 1),
        ('no_subtitle',        'size_no_subtitle',        'file_count_no_subtitle',        'resolution_no_subtitle',        0, 1),
    ]
    base_url = cfg('BASE_URL', 'https://javdb.com')

    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        for row in rows:
            href = javdb_absolute_url(row.get('href') or '', base_url)
            cur = conn.execute(
                """INSERT INTO ReportMovies
                   (SessionId, Href, VideoCode, Page, Actor, Rate, CommentNumber)
                   VALUES (?, ?, ?, ?, ?, ?, ?)""",
                (session_id,
                 href, row.get('video_code'),
                 int(row['page']) if row.get('page') else None,
                 row.get('actor'),
                 float(row['rate']) if row.get('rate') else None,
                 int(row['comment_number']) if row.get('comment_number') else None),
            )
            rm_id = cur.lastrowid
            vc = row.get('video_code')
            for cat, size_cat, fc_cat, res_cat, sub_ind, cen_ind in _CATS:
                magnet = (row.get(cat) or '').strip()
                if magnet:
                    conn.execute(
                        """INSERT INTO ReportTorrents
                           (ReportMovieId, VideoCode, MagnetUri,
                            SubtitleIndicator, CensorIndicator,
                            ResolutionType, Size, FileCount)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                        (rm_id, vc, magnet, sub_ind, cen_ind,
                         row.get(res_cat),
                         row.get(size_cat),
                         int(row.get(fc_cat, 0) or 0)),
                    )
        return len(rows)


def db_get_report_rows(
    session_id: str,
    db_path: Optional[str] = None,
) -> List[dict]:
    """Get all rows for a session as flat dicts (backward compatible).

    Aggregates ReportMovies + ReportTorrents back into the legacy format
    with hacked_subtitle, subtitle, etc. columns.

    Args:
        session_id: Session identifier
        db_path: Database path (defaults to REPORTS_DB_PATH)

    Returns:
        List of movie dicts with aggregated torrent data
    """
    _ensure_imports()

    def indicators_to_category(sub_ind: int, cen_ind: int) -> str:
        """Map (SubtitleIndicator, CensorIndicator) to category name."""
        if sub_ind == 1 and cen_ind == 0:
            return 'hacked_subtitle'
        elif sub_ind == 0 and cen_ind == 0:
            return 'hacked_no_subtitle'
        elif sub_ind == 1 and cen_ind == 1:
            return 'subtitle'
        else:  # sub_ind == 0 and cen_ind == 1
            return 'no_subtitle'

    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        movies = conn.execute(
            "SELECT * FROM ReportMovies WHERE SessionId = ? ORDER BY Id",
            (session_id,),
        ).fetchall()

        result = []
        for m in movies:
            m = dict(m)
            flat = {
                'href': m.get('Href', ''),
                'video_code': m.get('VideoCode', ''),
                'page': m.get('Page'),
                'actor': m.get('Actor', ''),
                'rate': m.get('Rate'),
                'comment_number': m.get('CommentNumber'),
                'hacked_subtitle': '',
                'hacked_no_subtitle': '',
                'subtitle': '',
                'no_subtitle': '',
                'size_hacked_subtitle': '',
                'size_hacked_no_subtitle': '',
                'size_subtitle': '',
                'size_no_subtitle': '',
                'file_count_hacked_subtitle': 0,
                'file_count_hacked_no_subtitle': 0,
                'file_count_subtitle': 0,
                'file_count_no_subtitle': 0,
                'resolution_hacked_subtitle': None,
                'resolution_hacked_no_subtitle': None,
                'resolution_subtitle': None,
                'resolution_no_subtitle': None,
            }
            torrents = conn.execute(
                "SELECT * FROM ReportTorrents WHERE ReportMovieId = ?",
                (m['Id'],),
            ).fetchall()
            for t in torrents:
                t = dict(t)
                cat = indicators_to_category(t['SubtitleIndicator'], t['CensorIndicator'])
                flat[cat] = t.get('MagnetUri', '')
                flat[f'size_{cat}'] = t.get('Size', '')
                flat[f'file_count_{cat}'] = t.get('FileCount', 0)
                flat[f'resolution_{cat}'] = t.get('ResolutionType')
            result.append(flat)
        return result


def db_get_latest_session(
    report_type: Optional[str] = None,
    db_path: Optional[str] = None,
) -> Optional[dict]:
    """Get the latest session (by Id DESC).

    Args:
        report_type: Optional filter by report type
        db_path: Database path (defaults to REPORTS_DB_PATH)

    Returns:
        Session dict or None if no sessions found
    """
    _ensure_imports()

    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        if report_type is not None:
            row = conn.execute(
                "SELECT * FROM ReportSessions WHERE ReportType = ? "
                "ORDER BY Id DESC LIMIT 1",
                (report_type,),
            ).fetchone()
        else:
            row = conn.execute(
                "SELECT * FROM ReportSessions ORDER BY Id DESC LIMIT 1"
            ).fetchone()
    return dict(row) if row else None


# ── Rollback interface ───────────────────────────────────────────────────


def rollback_reports_for_session(
    session_id: str,
    db_path: Optional[str] = None,
) -> int:
    """Rollback report rows for a session.

    Deletes rows from ReportSessions, ReportMovies, and ReportTorrents
    (cascading delete handles ReportTorrents automatically if FK is set).

    Args:
        session_id: Session identifier
        db_path: Database path (defaults to REPORTS_DB_PATH)

    Returns:
        Number of rows deleted from ReportSessions
    """
    _ensure_imports()

    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        # Delete ReportMovies (ReportTorrents cascade via FK)
        conn.execute(
            "DELETE FROM ReportMovies WHERE SessionId = ?",
            (session_id,),
        )
        # Delete ReportSessions
        cur = conn.execute(
            "DELETE FROM ReportSessions WHERE Id = ?",
            (session_id,),
        )
        return cur.rowcount or 0


# ── Delegating wrappers (pending full migration) ────────────────────────


def db_find_in_progress_session_ids_for_run_csv(
    run_id: str,
    run_attempt: Optional[int],
    csv_filename: str,
    *,
    db_path: Optional[str] = None,
) -> List[str]:
    """Return ``in_progress`` SessionIds for the same (RunId, RunAttempt, CSVFilename).

    Used by the spider self-check to distinguish *legitimate* sibling
    sessions in the same workflow run from a *true* duplicate.
    """
    _ensure_imports()
    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        if run_attempt is None:
            rows = conn.execute(
                "SELECT Id FROM ReportSessions "
                "WHERE Status='in_progress' AND RunId=? AND CSVFilename=?",
                (run_id, csv_filename),
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT Id FROM ReportSessions WHERE Status='in_progress' "
                "AND RunId=? AND RunAttempt=? AND CSVFilename=?",
                (run_id, int(run_attempt), csv_filename),
            ).fetchall()
    return [r['Id'] for r in rows]


def db_get_latest_session_local(
    report_type: Optional[str] = None, db_path: Optional[str] = None,
) -> Optional[dict]:
    """SQLite-only counterpart to :func:`db_get_latest_session`."""
    _ensure_imports()
    with _get_local_sqlite_db(db_path or _REPORTS_DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        if report_type is not None:
            row = conn.execute(
                "SELECT * FROM ReportSessions WHERE ReportType = ? "
                "ORDER BY Id DESC LIMIT 1",
                (report_type,),
            ).fetchone()
        else:
            row = conn.execute(
                "SELECT * FROM ReportSessions ORDER BY Id DESC LIMIT 1"
            ).fetchone()
        return dict(row) if row else None


def db_get_session_run_identity(
    session_id: str,
    *,
    db_path: Optional[str] = None,
) -> Optional[Tuple[Optional[str], Optional[int]]]:
    """Return ``(RunId, RunAttempt)`` for *session_id*, or ``None`` if absent."""
    _ensure_imports()
    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        row = conn.execute(
            "SELECT RunId, RunAttempt FROM ReportSessions WHERE Id=?",
            (session_id,),
        ).fetchone()
    if row is None:
        return None
    return (row["RunId"], row["RunAttempt"])


def db_pending_session_stats(
    session_id: str,
    *,
    db_path: Optional[str] = None,
) -> Dict[str, int]:
    """Snapshot pending-table counts for *session_id* (Phase 2 verify).

    Returns dict with keys: pending_residual_count, pending_applied_count,
    pending_total_count.
    """
    _ensure_imports()
    counts = {
        "pending_residual_count": 0,
        "pending_applied_count": 0,
        "pending_total_count": 0,
    }
    with _get_db(db_path or _HISTORY_DB_PATH) as conn:
        for tbl in (
            "PendingMovieHistoryWrites",
            "PendingTorrentHistoryWrites",
        ):
            try:
                row = conn.execute(
                    f"SELECT "
                    f"  SUM(CASE WHEN ApplyState='pending' THEN 1 ELSE 0 END) "
                    f"    AS pending_n, "
                    f"  SUM(CASE WHEN ApplyState='applied' THEN 1 ELSE 0 END) "
                    f"    AS applied_n "
                    f"FROM {tbl} WHERE SessionId=?",
                    (session_id,),
                ).fetchone()
            except _DB_OPERATIONAL_ERRORS:
                continue
            if row is None:
                continue
            counts["pending_residual_count"] += int(row["pending_n"] or 0)
            counts["pending_applied_count"] += int(row["applied_n"] or 0)
    counts["pending_total_count"] = (
        counts["pending_residual_count"] + counts["pending_applied_count"]
    )
    return counts


def db_find_sessions_by_run(
    run_id: str,
    run_attempt: Optional[int] = None,
    *,
    reports_db_path: Optional[str] = None,
    history_db_path: Optional[str] = None,
) -> List[str]:
    """Return every session id touched by a (RunId, RunAttempt) workflow run.

    Looks at ReportSessions first, then unions in audit tables for any
    rows tagged with the run identity but whose owning session row is missing.
    """
    _ensure_imports()
    found: set = set()
    with _get_db(reports_db_path or _REPORTS_DB_PATH) as conn:
        if run_attempt is None:
            rows = conn.execute(
                "SELECT Id FROM ReportSessions WHERE RunId=?", (run_id,),
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT Id FROM ReportSessions WHERE RunId=? AND RunAttempt=?",
                (run_id, int(run_attempt)),
            ).fetchall()
        for r in rows:
            found.add(r['Id'])

    with _get_db(history_db_path or _HISTORY_DB_PATH) as conn:
        for table in ('MovieHistoryAudit', 'TorrentHistoryAudit'):
            try:
                if run_attempt is None:
                    rows = conn.execute(
                        f"SELECT DISTINCT SessionId FROM {table} WHERE RunId=?",
                        (run_id,),
                    ).fetchall()
                else:
                    rows = conn.execute(
                        f"SELECT DISTINCT SessionId FROM {table} "
                        f"WHERE RunId=? AND RunAttempt=?",
                        (run_id, int(run_attempt)),
                    ).fetchall()
            except _DB_OPERATIONAL_ERRORS:
                continue
            for r in rows:
                if r['SessionId'] is not None:
                    found.add(r['SessionId'])

    return sorted(found)


def db_begin_finalize_session(
    session_id: str,
    *,
    db_path: Optional[str] = None,
) -> int:
    """Flip ``Status`` from ``in_progress`` to ``finalizing``."""
    _ensure_imports()
    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        cur = conn.execute(
            "UPDATE ReportSessions SET Status='finalizing' "
            "WHERE Id=? AND Status='in_progress'",
            (session_id,),
        )
        return cur.rowcount or 0


def db_finish_commit_session(
    session_id: str,
    *,
    db_path: Optional[str] = None,
) -> int:
    """Flip ``Status`` from ``finalizing`` to ``committed``."""
    _ensure_imports()
    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        cur = conn.execute(
            "UPDATE ReportSessions SET Status='committed' "
            "WHERE Id=? AND Status='finalizing'",
            (session_id,),
        )
        return cur.rowcount or 0


def db_get_sessions_by_date(
    report_date: str,
    report_type: Optional[str] = None,
    db_path: Optional[str] = None,
) -> List[dict]:
    """Get all sessions for a given date."""
    _ensure_imports()
    with _get_db(db_path or _REPORTS_DB_PATH) as conn:
        if report_type:
            rows = conn.execute(
                "SELECT * FROM ReportSessions WHERE ReportDate = ? AND ReportType = ? ORDER BY Id",
                (report_date, report_type),
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM ReportSessions WHERE ReportDate = ? ORDER BY Id",
                (report_date,),
            ).fetchall()
        return [dict(r) for r in rows]

